source('src/transcriptomics/helpers.R')
stopifnot(identical(names(make_rank(c(2,2,NA,-1),c('B','A','C','D'))),c('A','B','D')))
stopifnot(inherits(try(make_rank(c(1,2),c('A','A')),silent=TRUE),'try-error'))
stopifnot(all.equal(family_bh(c(.01,.04,NA),3),c(.03,.06,1)))
stopifnot(classify_robustness(.01,1,c(1,2,3),c(1,1,1))=='robust')
stopifnot(classify_robustness(.01,1,c(1,-1,3),c(1,1,1))=='block-dependent')
stopifnot(classify_robustness(.01,1,c(1,NA,3),c(1,1,1))=='directionally consistent but uncertain')
stopifnot(classify_robustness(.5,1,c(1,-1,3),c(1,1,1))=='unsupported')
sat<-data.frame(x=factor(1:3));stopifnot(inherits(try(assert_design(sat,~x),silent=TRUE),'try-error'))
cat('Eight transcriptomic invariant checks passed.\n')
