// Run against the built static server. BROWSER_PATH may select an existing Chromium.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const atlasURL=process.env.ATLAS_URL||'http://127.0.0.1:4173';
const origin=new URL(atlasURL).origin,externalRequests=[],failedRequests=[],requests=[];
await page.route('**/*',route=>{const url=route.request().url();requests.push(url);if(new URL(url).origin!==origin){externalRequests.push(url);return route.abort();}return route.continue();});
page.on('requestfailed',r=>failedRequests.push({url:r.url(),failure:r.failure()}));
page.on('response',r=>{if(r.status()>=400)failedRequests.push({url:r.url(),status:r.status()})});
await page.goto(atlasURL);
await page.getByRole('button',{name:'OXPHOS landscape',exact:true}).waitFor();
assert.equal(await page.locator('.matrix-cell').count(),15);
await mkdir('screenshots',{recursive:true});
await page.screenshot({path:'screenshots/overview.png',fullPage:true});
await page.getByRole('button',{name:'OXPHOS landscape',exact:true}).click();
assert.equal(await page.locator('.gene-row').count(),113);
await page.getByRole('button',{name:'Inspect NDUFB7, Respiratory complex I',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.gene-symbol')?.textContent==='NDUFB7'&&document.querySelector('.gene-detail')?.textContent.includes('ENSG'));
assert.match(await page.locator('.gene-detail').innerText(),/2\.507/);
await page.screenshot({path:'screenshots/landscape.png',fullPage:true});
await page.getByLabel('Functional group',{exact:true}).selectOption('Respiratory complex II');
assert.equal(await page.locator('.gene-row').count(),3);
await page.getByRole('button',{name:'Gene explorer',exact:true}).click();
await page.getByLabel('Search genes').fill('ATP5F1A');
await page.getByRole('button',{name:/ATP5A1/}).click();
await page.waitForFunction(()=>document.querySelector('.gene-symbol')?.textContent==='ATP5A1');
assert.match(await page.locator('.gene-detail').innerText(),/Alias sensitivity/);
await page.getByLabel('Search genes').fill('no-such-gene-xyz');
assert.match(await page.locator('.gene-results').innerText(),/No matching filtered gene/);
await page.getByRole('button',{name:'Pathways',exact:true}).click();
await page.getByLabel('Pathway',{exact:true}).selectOption('REACTOME_GLUTATHIONE_SYNTHESIS_AND_RECYCLING');
assert.match(await page.locator('.atlas-body').innerText(),/Untestable/);
await page.getByLabel('Pathway',{exact:true}).selectOption('HALLMARK_OXIDATIVE_PHOSPHORYLATION');
await page.getByLabel('Contrast',{exact:true}).selectOption('day3_vs_day1');
assert.match(await page.locator('.result-summary').innerText(),/block-dependent/);
await page.getByRole('button',{name:'Robustness',exact:true}).click();
assert.equal(await page.locator('tbody').first().locator('tr').count(),10);
const dl=page.waitForEvent('download');await page.getByRole('button',{name:'↓ Download data',exact:true}).first().click();assert.equal((await dl).suggestedFilename(),'all-robustness-variants.csv');
await page.getByRole('button',{name:'Pathways',exact:true}).click();
await page.getByLabel('Evidence tier').selectOption('exploratory');
assert.equal(await page.getByLabel('Pathway',{exact:true}).locator('option').count(),2);
await page.getByLabel('Pathway',{exact:true}).selectOption('HALLMARK_DNA_REPAIR');
assert.match(await page.locator('.result-summary').innerText(),/6-test exploratory/);
await page.getByRole('button',{name:'DNA maintenance',exact:true}).click();
assert.equal(await page.locator('.dna-row').count(),30);
await page.getByLabel('Telomere annotation').selectOption('Packaging / protection');
assert.equal(await page.locator('.dna-row').count(),3);
await page.getByRole('button',{name:'Inspect DNA-maintenance gene TINF2',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.gene-symbol')?.textContent==='TINF2'&&document.querySelector('.gene-detail')?.textContent.includes('ENSG'));
await page.getByLabel('Telomere annotation').selectOption('All genes');
await page.getByLabel('DNA follow-up contrast').selectOption('day3_vs_control');
assert.match(await page.locator('.atlas-body').innerText(),/1.395/);
await page.getByText('Inspect all 240 follow-up results',{exact:true}).click();
assert.equal(await page.locator('details').first().locator('tbody tr').count(),240);
await page.getByText('Inspect all 240 follow-up results',{exact:true}).click();
await page.screenshot({path:'screenshots/dna-maintenance.png',fullPage:true});
await page.getByRole('button',{name:'Methods & sources',exact:true}).click();
assert.match(await page.locator('.hash-record').innerText(),/2026-09-18T07:56:56/);
await page.setViewportSize({width:390,height:844});
for(const name of ['Overview','OXPHOS landscape','Gene explorer','Pathways','Robustness','DNA maintenance','Methods & sources']){
 await page.getByRole('button',{name,exact:true}).click();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Mobile overflow in ${name}`);
}
await page.getByRole('button',{name:'Overview',exact:true}).click();await page.screenshot({path:'screenshots/mobile.png',fullPage:true});
const fonts=await page.evaluate(()=>({body:getComputedStyle(document.body).fontFamily,title:getComputedStyle(document.querySelector('h1')).fontFamily}));
assert.match(fonts.body,/system-ui/);assert.doesNotMatch(fonts.title,/Georgia|Source Serif/);
assert.deepEqual(externalRequests,[]);assert.deepEqual(failedRequests,[]);assert.deepEqual(errors,[]);
await writeFile('screenshots/browser-check.json',JSON.stringify({passed:true,checks:['primary family','113 heatmap rows','gene selection','functional filter','alias lookup','missing gene','untestable secondary set','mixed temporal result','all sensitivity variants','CSV download','provenance','seven mobile views','exploratory family','30-gene DNA view','multi-membership annotation filter','24-test family','240 follow-up variants','system typography','external requests blocked'],browser:await browser.version(),fonts,externalRequests,failedRequests,requestCount:requests.length,requestOrigins:[...new Set(requests.map(u=>new URL(u).origin))],errors},null,2));
console.log('Browser checks passed; screenshots saved.');await browser.close();
