// Run against the built static server. BROWSER_PATH may select an existing Chromium.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.addInitScript(()=>{Object.defineProperty(navigator,'share',{configurable:true,value:async payload=>{window.__lastSharedPayload=payload;}});});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const atlasURL=process.env.ATLAS_URL||'http://127.0.0.1:4173';
const origin=new URL(atlasURL).origin,externalRequests=[],failedRequests=[],requests=[];
await page.route('**/*',route=>{const url=route.request().url();requests.push(url);if(new URL(url).origin!==origin){externalRequests.push(url);return route.abort();}return route.continue();});
page.on('requestfailed',r=>failedRequests.push({url:r.url(),failure:r.failure()}));
page.on('response',r=>{if(r.status()>=400)failedRequests.push({url:r.url(),status:r.status()})});
await page.goto(atlasURL);
await page.getByRole('button',{name:'OXPHOS landscape',exact:true}).waitFor();
assert.equal(await page.locator('.header-repository').getAttribute('href'),'https://github.com/psilocybin-research/psilocin-human-neuron-transcriptomics');
assert.equal(await page.locator('.release').innerText(),'v1.0.1');
assert.match(await page.locator('.header-study').innerText(),/Source study · Schmidt et al\. \(2026\)/i);
assert.equal(await page.locator('.header-study').getAttribute('href'),'https://doi.org/10.7554/eLife.104006');
assert.match(await page.locator('.author-line').innerText(),/Germann, Christopher B\./);
assert.equal(await page.locator('.orcid').getAttribute('href'),'https://orcid.org/0000-0002-1573-4651');
assert.equal(await page.locator('.author-line sup').count(),0);
assert.doesNotMatch(await page.locator('.affiliation').innerText(),/^¹/);
const headerIcons=await page.evaluate(()=>{const github=document.querySelector('.header-repository svg').getBoundingClientRect(),orcid=document.querySelector('.orcid svg').getBoundingClientRect();return{github:[github.width,github.height],orcid:[orcid.width,orcid.height]};});
assert.deepEqual(headerIcons.github,[22,22]);assert.deepEqual(headerIcons.orcid,[22,22]);
assert.equal(await page.locator('.native-share').count(),1);
assert.equal(await page.locator('.native-share').getAttribute('aria-label'),'Share the current atlas analysis');
assert.equal(await page.locator('.native-share svg').count(),1);
assert.equal(await page.locator('.boundary').count(),1);
assert.match(await page.locator('.boundary').innerText(),/^Interpretation boundary/);
const boundaryOrder=await page.evaluate(()=>{const boundary=document.querySelector('.boundary'),exploratory=[...document.querySelectorAll('.section-heading h2')].find(node=>node.textContent==='Exploratory DNA-maintenance evidence')?.closest('.section-heading');return Boolean(boundary&&exploratory&&(exploratory.compareDocumentPosition(boundary)&Node.DOCUMENT_POSITION_FOLLOWING));});
assert.equal(boundaryOrder,true);
const fullscreenSupported=await page.evaluate(()=>Boolean((document.fullscreenEnabled||document.webkitFullscreenEnabled)&&(Element.prototype.requestFullscreen||Element.prototype.webkitRequestFullscreen)));
assert.equal((await page.locator('.figure-fullscreen').count())>0,fullscreenSupported);
assert.ok(!(await page.locator('body').innerText()).includes('A companion to the Schmidt secondary analysis'));
const palette=await page.evaluate(()=>({background:getComputedStyle(document.body).backgroundColor,standfirst:getComputedStyle(document.querySelector('.standfirst')).color}));
assert.equal(palette.background,'rgb(255, 255, 255)');
const scrollTop=page.locator('.scroll-top');
await scrollTop.waitFor({state:'attached'});
assert.equal(await scrollTop.getAttribute('aria-label'),'Scroll to top');
assert.equal(await scrollTop.isVisible(),false);
await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));
await page.waitForFunction(()=>{const b=document.querySelector('.scroll-top');return b&&!b.hidden});
assert.equal(await scrollTop.evaluate(el=>getComputedStyle(el).mixBlendMode),'difference');
assert.match(await scrollTop.evaluate(el=>getComputedStyle(el).backgroundImage),/conic-gradient/);
await scrollTop.click();
await page.waitForFunction(()=>window.scrollY<5);
assert.equal(await page.locator('.matrix-cell').count(),15);
const layout=await page.evaluate(()=>{const button=document.querySelector('.figure-fullscreen'),toolbar=document.querySelector('.figure-toolbar'),matrix=document.querySelector('.matrix-scroll');const b=button.getBoundingClientRect(),t=toolbar.getBoundingClientRect(),m=matrix.getBoundingClientRect();return{position:getComputedStyle(button).position,toolbarBeforePlot:t.bottom<=m.top,buttonBeforePlot:b.bottom<=m.top,matrixOverflowY:getComputedStyle(matrix).overflowY,headlineWhiteSpace:getComputedStyle(document.querySelector('.hero h1')).whiteSpace};});
assert.equal(layout.position,'static');assert.equal(layout.toolbarBeforePlot,true);assert.equal(layout.buttonBeforePlot,true);assert.equal(layout.matrixOverflowY,'hidden');assert.equal(layout.headlineWhiteSpace,'normal');
await mkdir('screenshots',{recursive:true});
await page.getByRole('button',{name:'OXPHOS landscape',exact:true}).click();
assert.equal(await page.locator('.boundary').count(),0);
assert.equal(await page.locator('.gene-row').count(),113);
await page.getByRole('button',{name:'Inspect NDUFB7, Respiratory complex I',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.gene-symbol')?.textContent==='NDUFB7'&&document.querySelector('.gene-detail')?.textContent.includes('ENSG'));
assert.match(await page.locator('.gene-detail').innerText(),/2\.507/);
await page.locator('.native-share').click();
const sharedLandscape=await page.evaluate(()=>window.__lastSharedPayload);
assert.match(sharedLandscape.title,/OXPHOS landscape · Gene: NDUFB7/);
assert.match(sharedLandscape.url,/#view=landscape&gene=NDUFB7/);
await page.screenshot({path:'screenshots/landscape.png',fullPage:true});
assert.equal(await page.getByRole('button',{name:'Print The OXPHOS landscape'}).count(),1);
if(fullscreenSupported){
 const fullscreen=await page.evaluate(()=>{const shell=[...document.querySelectorAll('.figure-shell')].find(x=>x.querySelector('.landscape-layout'));const detail=shell.querySelector('.gene-detail');const toolbar=shell.querySelector('.figure-toolbar');return {detail:detail?.innerText,toolbarAbove:toolbar.getBoundingClientRect().bottom<=shell.querySelector('.landscape-layout').getBoundingClientRect().top,background:getComputedStyle(shell).backgroundColor};});
 assert.equal(fullscreen.background,'rgb(255, 255, 255)');assert.match(fullscreen.detail,/NDUFB7/);assert.equal(fullscreen.toolbarAbove,true);
}
await page.getByLabel('Functional group',{exact:true}).selectOption('Respiratory complex II');
assert.equal(await page.locator('.gene-row').count(),3);
await page.getByRole('button',{name:'Gene explorer',exact:true}).click();
await page.getByLabel('Search genes').fill('ATP5F1A');
await page.getByRole('button',{name:/ATP5A1/}).click();
await page.waitForFunction(()=>document.querySelector('.gene-symbol')?.textContent==='ATP5A1');
assert.match(await page.locator('.gene-detail').innerText(),/Alias sensitivity/);
await page.getByLabel('Search genes').fill('no-such-gene-xyz');
assert.match(await page.locator('.gene-results').innerText(),/No matching filtered gene/);
await page.getByRole('button',{name:'Pathways',exact:true}).click();
await page.getByLabel('Pathway',{exact:true}).selectOption('REACTOME_GLUTATHIONE_SYNTHESIS_AND_RECYCLING');
assert.match(await page.locator('.atlas-body').innerText(),/Untestable/);
await page.getByLabel('Pathway',{exact:true}).selectOption('HALLMARK_OXIDATIVE_PHOSPHORYLATION');
await page.getByLabel('Contrast',{exact:true}).selectOption('day3_vs_day1');
assert.match(await page.locator('.result-summary').innerText(),/block-dependent/);
await page.getByRole('button',{name:'Robustness',exact:true}).click();
assert.equal(await page.locator('tbody').first().locator('tr').count(),10);
const dl=page.waitForEvent('download');await page.getByRole('button',{name:'↓ Download data',exact:true}).first().click();assert.equal((await dl).suggestedFilename(),'all-robustness-variants.csv');
await page.getByRole('button',{name:'Pathways',exact:true}).click();
await page.getByLabel('Evidence tier').selectOption('exploratory');
assert.equal(await page.getByLabel('Pathway',{exact:true}).locator('option').count(),2);
await page.getByLabel('Pathway',{exact:true}).selectOption('HALLMARK_DNA_REPAIR');
assert.match(await page.locator('.result-summary').innerText(),/6-test exploratory/);
await page.getByRole('button',{name:'DNA maintenance',exact:true}).click();
assert.equal(await page.locator('.dna-row').count(),30);
await page.getByLabel('Telomere annotation').selectOption('Packaging / protection');
assert.equal(await page.locator('.dna-row').count(),3);
await page.getByRole('button',{name:'Inspect DNA-maintenance gene TINF2',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.gene-symbol')?.textContent==='TINF2'&&document.querySelector('.gene-detail')?.textContent.includes('ENSG'));
await page.getByLabel('Telomere annotation').selectOption('All genes');
await page.getByLabel('DNA follow-up contrast').selectOption('day3_vs_control');
assert.match(await page.locator('.atlas-body').innerText(),/1.395/);
await page.getByText('Inspect all 240 follow-up results',{exact:true}).click();
assert.equal(await page.locator('details').first().locator('tbody tr').count(),240);
await page.getByText('Inspect all 240 follow-up results',{exact:true}).click();
await page.getByRole('button',{name:'Methods & sources',exact:true}).click();
assert.match(await page.locator('.hash-record').innerText(),/2026-09-18T07:56:56/);
await page.setViewportSize({width:390,height:844});
for(const name of ['Overview','OXPHOS landscape','Gene explorer','Pathways','Robustness','DNA maintenance','Methods & sources']){
 await page.getByRole('button',{name,exact:true}).click();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Mobile overflow in ${name}`);
}
const fonts=await page.evaluate(()=>({body:getComputedStyle(document.body).fontFamily,title:getComputedStyle(document.querySelector('h1,h2,h3')).fontFamily}));
assert.match(fonts.body,/system-ui/);assert.doesNotMatch(fonts.title,/Georgia|Source Serif/);
assert.deepEqual(externalRequests,[]);assert.deepEqual(failedRequests,[]);assert.deepEqual(errors,[]);
await writeFile('screenshots/browser-check.json',JSON.stringify({passed:true,checks:['header repository and ORCID icons','interpretation boundary follows overview evidence','white high-contrast surface','scroll progress and return-to-top control','primary family','fullscreen landscape with selected-gene detail','print control','113 heatmap rows','gene selection','functional filter','alias lookup','missing gene','untestable secondary set','mixed temporal result','all sensitivity variants','CSV download','provenance','seven mobile views','exploratory family','30-gene DNA view','multi-membership annotation filter','24-test family','240 follow-up variants','system typography','external requests blocked'],browser:await browser.version(),fonts,palette,externalRequests,failedRequests,requestCount:requests.length,requestOrigins:[...new Set(requests.map(u=>new URL(u).origin))],errors},null,2));
console.log('Browser checks passed; screenshots saved.');await browser.close();
