import {contrasts,names,label,fmt,sci,color,edgeGenes,csvText} from './format.js';
const NS='http://www.w3.org/2000/svg';
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function svgNode(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
function svg(w,h,title){const n=svgNode('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':title,style:'font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;font-size:12px;fill:#43534b'});n.append(svgNode('title',{},title));return n;}
function text(s,x,y,t,attrs={}){s.append(svgNode('text',{x,y,...attrs},t));}
function line(s,x1,y1,x2,y2,attrs={}){s.append(svgNode('line',{x1,y1,x2,y2,stroke:'#d7dedf',...attrs}));}
function button(t,fn,cls=''){const b=el('button',cls,t);b.type='button';b.onclick=fn;return b;}
function download(filename,content,type='text/csv'){const url=URL.createObjectURL(new Blob([content],{type}));const a=el('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function downloadButton(rows,name){return button('↓ Download data',()=>download(name,csvText(rows)),'secondary');}
function note(t){return el('p','note',t);}
function heading(t,sub){const n=el('header','section-heading');n.append(el('h2','',t),el('p','',sub));return n;}
function select(title,values,current,fn){const wrap=el('label','control');wrap.append(el('span','',title));const s=el('select');s.setAttribute('aria-label',title);for(const[v,t]of values){const o=el('option','',t);o.value=v;s.append(o);}s.value=current;s.onchange=()=>fn(s.value);wrap.append(s);return wrap;}
function table(rows,cols){const w=el('div','table-scroll'),t=el('table'),head=el('thead'),tr=el('tr');for(const [,name]of cols)tr.append(el('th','',name));head.append(tr);t.append(head);const body=el('tbody');for(const r of rows){const row=el('tr');for(const[k,,format]of cols){const cell=el('td',typeof r[k]==='number'?'numeric':k==='gene'?'gene-symbol-cell':'',format?format(r[k],r):r[k]??'Not estimable');row.append(cell);}body.append(row);}t.append(body);w.append(t);return w;}
function status(s){return el('span',`status ${s==='robust'?'stable':s==='unsupported'?'unsupported':'mixed'}`,s||'Not classified');}
function scaleKey(limit,title){const box=el('div','scale-key');box.append(el('span','',title),el('i','gradient'),el('span','',`−${limit}  ·  0  ·  +${limit}`));return box;}

export function createAtlas(data,provenance,loadGenes){
 const root=el('div','atlas');let genesPromise;const getGenes=()=>genesPromise??=(loadGenes());
 const landscapeMap=new Map(data.landscape.map(g=>[g.gene,g]));
 const profileMap=new Map(data.landscape.map(g=>[g.gene,data.profiles.filter(p=>p.gene===g.gene)]));
 const tabs=[['overview','Overview'],['landscape','OXPHOS landscape'],['genes','Gene explorer'],['pathways','Pathways'],['robustness','Robustness'],['dna','DNA maintenance'],['methods','Methods & sources']];
 let tab='overview',selected='GPX4',pathway='HALLMARK_OXIDATIVE_PHOSPHORYLATION',contrast='day1_vs_control',group='All functions',pathwayTier='all';
 const params=new URLSearchParams(location.hash.slice(1));if(tabs.some(x=>x[0]===params.get('view')))tab=params.get('view');selected=params.get('gene')||selected;
 const top=el('header','masthead');const home=el('a','wordmark','PSILOCIN / TRANSCRIPTOMIC ATLAS');home.href='https://psilocybin-research.github.io/psilocin-human-neuron-transcriptomics/';const meta=el('div','masthead-meta');meta.append(el('span','release','SCHMIDT ET AL. (2026) REANALYSIS · VERSION 1.0.0'));const author=el('div','author-line');const authorLink=el('a','','Germann, Christopher B.');authorLink.href='https://zenodo.org/search?q=metadata.creators.person_or_org.name:%22Germann,+Christopher+B.%22';authorLink.target='_blank';authorLink.rel='noopener';author.append(authorLink,el('sup','','1'));const orcid=el('a','orcid','ORCID: 0000-0002-1573-4651');orcid.href='https://orcid.org/0000-0002-1573-4651';orcid.target='_blank';orcid.rel='noopener';author.append(orcid);const affiliation=el('div','affiliation','¹ Faculty of Health, School of Medicine, University of Witten/Herdecke');const sourceData=el('a','header-source','Original source data · Dryad ↗');sourceData.href='https://doi.org/10.5061/dryad.xsj3tx9w3';sourceData.target='_blank';sourceData.rel='noopener';meta.append(author,affiliation,sourceData);top.append(home,meta);
 const nav=el('nav','tabs');nav.setAttribute('aria-label','Explorer sections');
 const body=el('div','atlas-body');const boundary=el('aside','boundary','Interpretation boundary · Three differentiation blocks, two genetic backgrounds. Control harvest days are unresolved; treatment-specific temporal change cannot be estimated.');
 const footer=el('footer','source-footer');footer.append(el('span','', 'Source study · Schmidt M, Hoffrichter A, Davoudi M, Horschitz S, Lau T, Meinhardt MW, Spanagel R, Ladewig J, Köhr G, Koch P. (2026). Psilocin fosters neuroplasticity in iPSC-derived human cortical neurons. eLife, 14, RP104006. '));const doi=el('a','','https://doi.org/10.7554/eLife.104006.3');doi.href='https://doi.org/10.7554/eLife.104006.3';doi.target='_blank';doi.rel='noopener';footer.append(doi);
 root.append(top,nav,boundary,body,footer);
 const toTop=button('↑',()=>window.scrollTo({top:0,behavior:'smooth'}),'scroll-top');toTop.setAttribute('aria-label','Scroll to top');toTop.title='Scroll to top';toTop.hidden=true;root.append(toTop);const updateScrollProgress=()=>{const range=document.documentElement.scrollHeight-innerHeight;const progress=range>0?Math.min(1,Math.max(0,scrollY/range)):0;toTop.style.setProperty('--scroll-progress',`${progress*360}deg`);toTop.hidden=progress<.06;};addEventListener('scroll',updateScrollProgress,{passive:true});addEventListener('resize',updateScrollProgress);updateScrollProgress();
 function go(next,gene){tab=next;if(gene)selected=gene;const q=new URLSearchParams({view:tab});if(tab==='genes'||tab==='landscape')q.set('gene',selected);history.replaceState(null,'',`#${q}`);render();}
 for(const [id,t]of tabs)nav.append(button(t,()=>go(id)));
 function render(){[...nav.children].forEach((b,i)=>{b.classList.toggle('active',tabs[i][0]===tab);b.setAttribute('aria-current',tabs[i][0]===tab?'page':'false');});body.replaceChildren();({overview,landscape,genesView,pathways,robustness,dna:dnaView,methods}[tab==='genes'?'genesView':tab])();}
 function overview(){
  const hero=el('section','hero');const intro=el('div');intro.append(el('div','eyebrow','HUMAN CORTICAL NEURONS · BULK RNA SEQUENCING'),el('h1','','A brief pulse.\nA broad transcriptional signature.'),el('p','standfirst','A 10-minute psilocin exposure is associated with later OXPHOS-centered transcription in the Schmidt dataset. Inspect the genes, pathway evidence and within-dataset checks behind that observation.'),button('Explore the 113-gene landscape →',()=>go('landscape'),'primary'));
  const metrics=el('div','metrics');for(const [v,t]of [['113','genes in the leading-edge union'],['89','leading-edge genes shared across days'],['3','differentiation blocks · 9 pooled profiles']]){const m=el('div');m.append(el('strong','',v),el('span','',t));metrics.append(m);}hero.append(intro,metrics);body.append(hero);
  const timeline=el('div','timeline');for(const [a,b]of [['10 min','10 µM psilocin'],['Washout','Exposure ends'],['Day 1 & Day 3','Later RNA sampling']]){const n=el('div');n.append(el('strong','',a),el('span','',b));timeline.append(n);}body.append(timeline);
  const source=el('section','source-study');source.append(el('h2','','Source study'),el('p','','Independent secondary analysis of Schmidt M, Hoffrichter A, Davoudi M, Horschitz S, Lau T, Meinhardt MW, Spanagel R, Ladewig J, Köhr G, Koch P. (2026). Psilocin fosters neuroplasticity in iPSC-derived human cortical neurons. eLife, 14, RP104006.'));const article=el('a','source-link','Read the article ↗');article.href='https://doi.org/10.7554/eLife.104006.3';article.target='_blank';article.rel='noopener';source.append(article);body.append(source);
  body.append(heading('The complete primary result','Five prespecified Hallmark sets × three contrasts. The color shows NES; the label shows the frozen directional classification.'));
  const p=data.pathways.filter(p=>p.tier==='primary');const mat=el('div','pathway-matrix');mat.append(el('div'));for(const c of data.contrasts)mat.append(el('div','matrix-head',contrasts[c]));
  for(const id of Object.keys(names)){mat.append(el('div','matrix-row',label(id)));for(const c of data.contrasts){const p1=p.find(r=>r.pathway===id&&r.contrast===c);const cell=button('',()=>{pathway=id;contrast=c;pathwayTier='primary';go('pathways');},'matrix-cell');cell.style.background=color(p1.NES,3.6);cell.append(el('strong','',fmt(p1.NES)),el('small','',`15-test q = ${sci(p1.family_fdr)}`),status(p1.robustness));cell.setAttribute('aria-label',`${label(id)}, ${contrasts[c]}, NES ${fmt(p1.NES)}, ${p1.robustness}`);mat.append(cell);}}
  const scroll=el('div','matrix-scroll');scroll.append(mat);body.append(el('p','mobile-hint','Swipe the matrix horizontally to inspect all three contrasts.'),scroll,scaleKey(3.6,'NES'),note('“Robust” means same direction across the frozen block and RNA-quality checks, with primary q < 0.05. Gene-ranking q-values do not provide independent biological replication.'),downloadButton(p,'primary-15-tests.csv'));
  body.append(heading('Broad OXPHOS signal; narrower redox mechanism unresolved','The primary contribution is a distributed OXPHOS-centered signature at both sampled days: 95 and 107 leading-edge genes, 89 shared, with consistent direction across the frozen within-dataset checks. The separate post-primary targeted tier did not establish NRF2, glutathione or their joint NRF2–glutathione–PPP prediction as the specific mechanism; that narrower result does not negate the broader transcriptional finding.'));
  body.append(table(data.targeted,[['module','Target',v=>label(v)],['contrast','Contrast',v=>contrasts[v]],['method','Statistic type'],['estimate','Estimate',v=>fmt(v)],['family_fdr','8-test q',sci],['robustness','Classification']]));
 }
 function landscape(){
  body.append(heading('The OXPHOS landscape','All 113 leading-edge genes, grouped descriptively by function. Select a row to inspect its exact effects and nine expression profiles.'));
  const controls=el('div','controls');controls.append(select('Functional group',[['All functions','All functions'],...[...new Set(data.landscape.map(g=>g.functional_group))].map(v=>[v,v])],group,v=>{group=v;landscapeRender();}),scaleKey(2.5,'Expression · row z'),scaleKey(1.5,'Effect · log₂ fold change'));
  body.append(controls);const split=el('div','landscape-layout'),heat=el('div','heatmap-scroll'),detail=el('aside','gene-detail');split.append(heat,detail);body.append(split);
  function landscapeRender(){heat.replaceChildren();const rows=data.landscape.filter(g=>group==='All functions'||g.functional_group===group);const s=svg(680,60+rows.length*15+new Set(rows.map(g=>g.functional_group)).size*22,'Interactive OXPHOS expression and effect heatmap');s.classList.add('heatmap');
   const profileX=125,cell=32,fx=448;
   ['68_3 / B1','68_3 / B2','69_2 / B1'].forEach((t,i)=>text(s,profileX+i*100+46,14,t,{'text-anchor':'middle','font-weight':600}));
   for(let i=0;i<9;i++)text(s,profileX+i*cell+Math.floor(i/3)*4+15,35,['Ctrl','D1','D3'][i%3],{'text-anchor':'middle'});
   ['D1/C','D3/C','D3/D1'].forEach((t,i)=>text(s,fx+i*45+20,35,t,{'text-anchor':'middle'}));text(s,594,35,'LE');
   let groupOffset=0;rows.forEach((g,i)=>{if(i===0||g.functional_group!==rows[i-1].functional_group){text(s,8,59+i*15+groupOffset,g.functional_group,{'font-size':10,'font-weight':600});groupOffset+=22;}const y=46+i*15+groupOffset;const r=svgNode('g',{tabindex:0,role:'button','aria-label':`Inspect ${g.gene}, ${g.functional_group}`});r.classList.add('gene-row');r.append(svgNode('rect',{x:0,y,width:670,height:15,fill:g.gene===selected?'#edf3f1':'transparent'}));r.append(svgNode('text',{x:114,y:y+11,'text-anchor':'end'},g.gene));
    profileMap.get(g.gene).forEach((p,j)=>{const c=svgNode('rect',{x:profileX+j*cell+Math.floor(j/3)*4,y,width:cell-.4,height:14.5,fill:color(p.row_z)});c.append(svgNode('title',{},`${g.gene} · ${p.block} · ${p.condition}\nVST ${fmt(p.vst,4)} · row z ${fmt(p.row_z,4)}\nMean RIN ${fmt(p.RIN_mean)} · ${p.libraries_n} source libraries`));r.append(c);});
    [g.day1_log2fc,g.day3_log2fc,g.day3_minus_day1_log2fc].forEach((v,j)=>{const c=svgNode('rect',{x:fx+j*45,y,width:44.5,height:14.5,fill:color(v,1.5)});c.append(svgNode('title',{},`${g.gene} · ${contrasts[data.contrasts[j]]}\nlog₂ fold change ${fmt(v,5)}`));r.append(c);});
    r.append(svgNode('rect',{x:594,y,width:12,height:14,fill:g.leading_edge==='Shared'?'#243c3c':g.leading_edge==='Day 1 only'?'#56b4e9':'#d55e00'}));
    const choose=()=>{selected=g.gene;history.replaceState(null,'',`#view=landscape&gene=${selected}`);geneDetail(detail,selected);heat.querySelectorAll('.gene-row > rect:first-child').forEach(x=>x.setAttribute('fill','transparent'));r.firstChild.setAttribute('fill','#edf3f1');};r.onclick=choose;r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};s.append(r);
   });heat.append(s);geneDetail(detail,selected);
  }
  landscapeRender();body.append(note('LE: charcoal = shared; blue = Day 1 only; orange = Day 3 only. VST uses blind=FALSE. Row z-scores are scaled across all nine profiles and colors saturate at ±2.5; effect colors saturate at ±1.5. Functional filtering does not recalculate scaling or fit a model. Leading-edge selection makes this a descriptive view.'),downloadButton(data.profiles,'oxphos-nine-profile-expression.csv'),button('↓ Download heatmap SVG',()=>download('oxphos-landscape.svg',new XMLSerializer().serializeToString(heat.querySelector('svg')),'image/svg+xml'),'secondary'));
 }
 async function geneDetail(container,symbol){
  container.replaceChildren(el('div','eyebrow','GENE DETAIL'),el('h3','gene-symbol',symbol),note('Loading archived estimates…'));const token=symbol;container.dataset.gene=token;
  const genes=await getGenes();if(container.dataset.gene!==token||!container.isConnected)return;
  const alias=data.aliases.find(a=>a.current_symbol===symbol||a.source_symbol===symbol||a.selected_gene_id===symbol);
  const gene=genes.find(g=>g.id===symbol)||genes.find(g=>g.symbol===symbol&&g.selected)||genes.find(g=>g.symbol===symbol)||genes.find(g=>g.id===alias?.selected_gene_id);
  container.replaceChildren(el('div','eyebrow','GENE DETAIL'),el('h3','gene-symbol',gene?.symbol||symbol));
  if(!gene){container.append(note('This identifier is absent from the filtered gene results. Absence is not a null result.'));return;}
  container.append(el('p','identifier',gene.id));const info=landscapeMap.get(gene.symbol);if(info)container.append(el('p','',info.functional_group),status(info.leading_edge));
  if(alias)container.append(note(`Alias sensitivity: ${alias.source_symbol||'absent'} → ${alias.current_symbol}; ${alias.status}. These primary estimates retain source symbols.`));
  if(!gene.selected)container.append(note('This gene ID was not the representative selected for symbol-based ranking. Estimates below remain gene-level results.'));
  const effects=gene.effects.map((e,i)=>({...e,contrast:contrasts[data.contrasts[i]]}));
  const s=svg(340,174,`${gene.symbol} model estimates and approximate 95% Wald intervals`);const limit=Math.max(.5,...effects.filter(e=>e.log2FoldChange!==null&&e.lfcSE!==null).map(e=>Math.abs(e.log2FoldChange)+1.96*e.lfcSE));const x=v=>172+v/limit*148;
  line(s,x(0),20,x(0),134,{stroke:'#879998','stroke-dasharray':'3 3'});
  effects.forEach((e,i)=>{const y=40+i*42;text(s,4,y-10,['D1 / control','D3 / control','D3 / D1'][i]);if(e.log2FoldChange!==null&&e.lfcSE!==null){line(s,x(e.log2FoldChange-1.96*e.lfcSE),y,x(e.log2FoldChange+1.96*e.lfcSE),y,{stroke:'#236461','stroke-width':2});s.append(svgNode('circle',{cx:x(e.log2FoldChange),cy:y,r:4,fill:'#236461'}));}});
  [-limit,0,limit].forEach(v=>text(s,x(v),152,fmt(v),{'text-anchor':'middle'}));text(s,172,171,'log₂ fold change · approximate 95% Wald interval',{'text-anchor':'middle','font-size':10});container.append(s);
  container.append(table(effects,[['contrast','Contrast'],['log2FoldChange','log₂FC',v=>fmt(v,3)],['lfcSE','SE',v=>fmt(v,3)],['padj','Gene FDR',sci]]));
  const profiles=profileMap.get(gene.symbol);if(profiles){const ps=svg(340,174,`${gene.symbol} variance-stabilized expression across nine pooled profiles`);const lo=Math.min(...profiles.map(p=>p.vst))-.2,hi=Math.max(...profiles.map(p=>p.vst))+.2;const y=v=>130-(v-lo)/(hi-lo)*105;
   for(let k=0;k<3;k++){const vals=profiles.slice(k*3,k*3+3);const points=vals.map((p,j)=>`${58+j*112},${y(p.vst)}`).join(' ');ps.append(svgNode('polyline',{points,fill:'none',stroke:['#0072b2','#69a2b8','#d55e00'][k],'stroke-width':1.5}));vals.forEach((p,j)=>{const dot=svgNode('circle',{cx:58+j*112,cy:y(p.vst),r:4,fill:['#0072b2','#69a2b8','#d55e00'][k]});dot.append(svgNode('title',{},`${p.block}, ${p.condition}: VST ${fmt(p.vst,4)}; RIN ${fmt(p.RIN_mean)}; ${p.libraries_n} libraries`));ps.append(dot);});}
   ['Control','Day 1','Day 3'].forEach((t,j)=>text(ps,58+j*112,150,t,{'text-anchor':'middle'}));text(ps,3,20,fmt(hi));text(ps,3,134,fmt(lo));text(ps,170,171,'VST · pooled profiles, separate cultures',{'text-anchor':'middle','font-size':10});container.append(el('h4','','Nine pooled profiles'),ps,note('Lines link conditions within each block for comparison; cultures were not sampled longitudinally. Dark blue: 68_3/B1; light blue: 68_3/B2; orange: 69_2/B1.'));}
  else container.append(note('Nine-profile expression is included for the 113 OXPHOS leading-edge genes. This gene has archived model estimates only in this companion.'));
  const memberships=Object.entries(data.membership).filter(([,gs])=>gs.includes(gene.symbol)).map(([id])=>label(id));container.append(el('h4','','Frozen pathway memberships'),el('p','',memberships.join(' · ')||'No literal-symbol membership in the frozen sets.'));
  container.append(note('Intervals use the archived unshrunken coefficient ±1.96 × SE. Gene FDR is distinct from pathway-family q. Three blocks limit generalization.'),downloadButton(effects,`${gene.symbol}-model-estimates.csv`));
 }
 async function genesView(){
  body.append(heading('Gene explorer','Search all 21,154 filtered gene IDs, including the 21,098 representatives used for symbol-based ranking. Verified ATP5 aliases resolve to their original identifiers.'));
  const search=el('input');search.type='search';search.placeholder='Search symbol, Ensembl ID or verified alias…';search.setAttribute('aria-label','Search genes');search.value=selected;
  const layout=el('div','gene-layout'),results=el('div','gene-results'),detail=el('article','gene-detail');body.append(search,layout);layout.append(results,detail);geneDetail(detail,selected);
  const genes=await getGenes();if(!search.isConnected)return;
  function searchResults(){const q=search.value.trim().toUpperCase();const aliasIds=new Set(data.aliases.filter(a=>a.current_symbol.includes(q)).map(a=>a.selected_gene_id));const found=genes.filter(g=>g.symbol.toUpperCase().includes(q)||g.id.toUpperCase().includes(q)||aliasIds.has(g.id));results.replaceChildren(note(`${found.length.toLocaleString()} matches${found.length>60?' · showing first 60 alphabetically':''}`));found.sort((a,b)=>a.symbol.localeCompare(b.symbol));for(const g of found.slice(0,60)){const b=button('',()=>{selected=g.id;geneDetail(detail,g.id);history.replaceState(null,'',`#view=genes&gene=${encodeURIComponent(g.id)}`);},'gene-hit');b.append(el('strong','',g.symbol),el('small','',g.id),el('small','',g.selected?'Rank representative':'Nonrepresentative duplicate'));results.append(b);}if(!found.length)results.append(note('No matching filtered gene. Try its source symbol or Ensembl ID.'));}
  search.oninput=searchResults;searchResults();
 }
 function pathways(){
  body.append(heading('Pathway evidence','Browse frozen primary, secondary and exploratory sets. Curves reconstruct the archived weighted ranking score; q-values and classifications come directly from the result tables.'));
  const eligible=data.pathways.filter(p=>pathwayTier==='all'||p.tier===pathwayTier);if(!eligible.some(p=>p.pathway===pathway))pathway=eligible[0].pathway;const choices=[...new Map(eligible.map(p=>[p.pathway,[p.pathway,`${label(p.pathway)} · ${p.tier}`]])).values()];
  const controls=el('div','controls');controls.append(select('Evidence tier',[['all','All frozen tiers'],['primary','Primary · 15 tests'],['secondary','Secondary · 21 tests'],['exploratory','Exploratory · 6 tests']],pathwayTier,v=>{pathwayTier=v;render();}),select('Pathway',choices,pathway,v=>{pathway=v;render();}),select('Contrast',Object.entries(contrasts),contrast,v=>{contrast=v;render();}));body.append(controls);
  const row=eligible.find(p=>p.pathway===pathway&&p.contrast===contrast);if(!row)return;
  const summary=el('div','result-summary');summary.append(el('strong','',`NES ${fmt(row.NES)}`),el('span','',`${({primary:'15-test primary',secondary:'21-test secondary',exploratory:'6-test exploratory'})[row.tier]} q = ${sci(row.family_fdr)}`),status(row.robustness));body.append(summary);
  const curve=data.curves[pathway+'|'+contrast];
  if(curve){const s=svg(900,275,`${label(pathway)} weighted running enrichment`),points=curve.points;const low=Math.min(0,...points.map(p=>p[1]))-.04,high=Math.max(0,...points.map(p=>p[1]))+.04;const x=v=>60+v*8.05,y=v=>230-(v-low)/(high-low)*195;
   line(s,60,y(0),865,y(0),{stroke:'#9aabaa'});[0,25,50,75,100].forEach(v=>{line(s,x(v),30,x(v),230);text(s,x(v),250,`${v}%`,{'text-anchor':'middle'});});for(let i=0;i<4;i++){const v=low+(high-low)*i/3;text(s,49,y(v)+4,fmt(v),{'text-anchor':'end'});}for(const h of curve.hits)line(s,x(h),232,x(h),238,{stroke:'#367393','stroke-opacity':.2});s.append(svgNode('polyline',{points:points.map(([a,b])=>`${x(a)},${y(b)}`).join(' '),fill:'none',stroke:'#a34850','stroke-width':2.3}));text(s,450,273,'Position in ranked transcriptome',{'text-anchor':'middle'});body.append(s,note(`${row.size} mapped genes; ${edgeGenes(row).length} leading-edge genes. The curve is sampled for display with both extrema retained; the exported q-value is unchanged.`));}
  else body.append(note('Untestable under the frozen minimum set size of 15. A stored q=1 for this row is bookkeeping, not evidence for a biological null.'));
  body.append(downloadButton([row],'pathway-result.csv'),el('h3','','Leading-edge genes'));
  const chips=el('div','chips');for(const g of edgeGenes(row))chips.append(button(g,()=>go('genes',g)));body.append(chips,note('Gene overlap means pathway results are not independent confirmations. Choosing a contrast or gene here changes the display only.'));
 }
 function robustness(){
  body.append(heading('What “robust” means here','Direction agreement across the frozen block omissions and RNA-quality checks. Significance in every small subset was not required.'));
  const choices=[...new Map(data.pathways.map(p=>[p.pathway,[p.pathway,`${label(p.pathway)} · ${p.tier}`]])).values()];
  const controls=el('div','controls');controls.append(select('Pathway',choices,pathway,v=>{pathway=v;render();}),select('Contrast',Object.entries(contrasts),contrast,v=>{contrast=v;render();}));body.append(controls);
  const rows=data.sensitivities.filter(r=>r.pathway===pathway&&r.contrast===contrast);const all=Math.max(1,...rows.filter(r=>r.NES!==null).map(r=>Math.abs(r.NES)));const s=svg(900,rows.length*30+62,'Pathway normalized enrichment score across all archived variants');const x=v=>550+v/(all+.3)*300;
  line(s,x(0),15,x(0),rows.length*30+20,{stroke:'#647d7d','stroke-dasharray':'4 4'});
  rows.forEach((r,i)=>{const y=30+i*30;text(s,12,y+4,r.variant.replaceAll('__',' / ').replaceAll('_',' '));line(s,320,y,875,y,{stroke:'#edf0f0'});if(r.NES!==null){const dot=svgNode('circle',{cx:x(r.NES),cy:y,r:r.variant==='primary'?6:4,fill:r.variant.startsWith('block_')?'#9a6960':'#236461'});dot.append(svgNode('title',{},`${r.variant}\nNES ${fmt(r.NES,5)}\nFamily q ${sci(r.family_fdr)}`));s.append(dot);}else text(s,550,y,'Not estimable');});[-all,0,all].forEach(v=>text(s,x(v),rows.length*30+47,fmt(v),{'text-anchor':'middle'}));body.append(s,note('NES is a normalized gene-ranking enrichment statistic, not a biological-sample effect size. Brown points are descriptive single-block rankings; they do not increase the number of independent blocks.'),downloadButton(rows,'all-robustness-variants.csv'));
  body.append(table(rows,[['variant','Variant'],['NES','NES',v=>fmt(v,4)],['family_fdr','Within-variant family q',sci],['rank_kind','Rank type']]));
  if(pathway==='HALLMARK_OXIDATIVE_PHOSPHORYLATION'){body.append(el('h3','','Post-freeze alias sensitivity'),note('The alias-expanded OXPHOS comparison is a separate one-set sensitivity and never replaces the frozen 15-test primary q-values.'));const aliases=data.aliasSensitivity.filter(r=>r.contrast===contrast);body.append(table(aliases,[['variant','Variant'],['baseline_NES','Literal NES',v=>fmt(v,4)],['NES','Alias NES',v=>fmt(v,4)]]),downloadButton(aliases,'post-freeze-alias-sensitivity.csv'));}
 }
 function dnaView(){
  body.append(heading('DNA maintenance','The two frozen exploratory pathways, followed by a separately specified post hoc decomposition. These results remain subordinate to the primary metabolic analysis.'));
  body.append(el('aside','boundary','Transcriptional enrichment ≠ DNA repair activity or telomere preservation. Cell-cycle context and shared pathway membership complicate specificity.'));
  const frozen=data.pathways.filter(p=>p.tier==='exploratory');
  body.append(el('h3','','Frozen exploratory family · 6 tests'),table(frozen,[['pathway','Pathway',label],['contrast','Contrast',v=>contrasts[v]],['NES','NES',v=>fmt(v,3)],['family_fdr','6-test q',sci],['robustness','Direction class']]),downloadButton(frozen,'frozen-exploratory-6-tests.csv'));
  body.append(heading('Which genes carry the telomere signal?','All 30 genes in the two-day leading-edge union: 27 at Day 1, 25 at Day 3, 22 shared. Functional annotations overlap; they are not additional enrichment tests.'));
  const controls=el('div','controls');let filter='All genes';const mapHost=el('div','dna-map-scroll'),detail=el('aside','gene-detail');
  controls.append(select('Telomere annotation',[['All genes','All genes'],['Packaging / protection','Packaging / protection'],['Telomerase extension / RNP','Telomerase extension / RNP'],['C-strand synthesis','C-strand synthesis'],['Recombination / chromatin / TERRA','Recombination / chromatin / TERRA']],filter,v=>{filter=v;draw();}),scaleKey(1.5,'Effect · log₂ fold change'));
  body.append(controls);const layout=el('div','landscape-layout');layout.append(mapHost,detail);body.append(layout);
  function draw(){
   const rows=data.dna.decomposition.filter(g=>filter==='All genes'||g.modules.split(';').includes(filter));const s=svg(680,108+rows.length*22,'Telomere leading-edge genes, model effects and overlapping descriptive annotations');s.classList.add('dna-map');
   const columns=[['D1/Ctrl',137],['D3/Ctrl',197],['LE D1',265],['LE D3',310],['DNA',365],['Protect',425],['RNP',479],['C-strand',541],['TERRA',611]];
   columns.forEach(([v,x])=>text(s,x,38,v,{'text-anchor':'middle','font-size':11}));text(s,8,72,'Gene',{'font-weight':600});
   rows.forEach((g,i)=>{const y=86+i*22,r=svgNode('g',{role:'button',tabindex:0,'aria-label':`Inspect DNA-maintenance gene ${g.gene}`});r.classList.add('dna-row');r.append(svgNode('text',{x:8,y:y+15},g.gene));
    [g.day1_log2fc,g.day3_log2fc].forEach((v,j)=>{const c=svgNode('rect',{x:110+j*60,y,width:54,height:21,fill:color(v,1.5)});c.append(svgNode('title',{},`${g.gene} · ${j?'Day 3':'Day 1'} log₂FC ${fmt(v,5)}`));r.append(c);});
    const bits=[g.day1_le,g.day3_le,g.dna_member,g.modules.includes('Packaging'),g.reaction_ids.includes('R-HSA-164616'),g.modules.includes('C-strand'),g.reaction_ids.includes('R-HSA-9670149')];
    bits.forEach((hit,j)=>{const c=svgNode('rect',{x:columns[j+2][1]-8,y:y+3,width:16,height:16,fill:hit?'#365c53':'#edf0ed'});c.append(svgNode('title',{},`${columns[j+2][0]}: ${hit?'member':'not annotated'}`));r.append(c);});
    const choose=()=>geneDetail(detail,g.gene);r.onclick=choose;r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};s.append(r);
   });mapHost.replaceChildren(s);
  }
  draw();geneDetail(detail,'ACD');
  body.append(note('DNA marks membership in the entire frozen Hallmark DNA-repair set. Protect: packaging/protection; RNP: telomerase RNP assembly participants; C-strand: synthesis; TERRA: transcription-reaction participants, including associated complexes. Child-set membership uses MSigDB 2026.1.Hs. Packaging (absent from that GMT) and reaction annotations use the recorded Reactome 97 snapshot. Membership does not measure telomerase or TERRA activity.'),downloadButton(data.dna.decomposition,'telomere-30-gene-decomposition.csv'));
  body.append(el('h3','','Gene-set redundancy'),table(data.dna.overlap,[['scope','Comparison'],['dna_n','DNA repair'],['telomere_n','Telomere'],['shared_n','Shared'],['jaccard','Jaccard',v=>fmt(v,3)],['fraction_telomere','Fraction of telomere',v=>fmt(v,3)]]),downloadButton(data.dna.overlap,'dna-telomere-overlap.csv'));
  body.append(heading('Overlap removal and cell-cycle context','Post hoc family: eight sets × three contrasts, 24-test BH correction. All results and ten variants are retained. Positive enrichment after subtraction does not establish biological independence.'));
  const follow=el('div');body.append(follow);let dc='day1_vs_control';
  const renderTests=()=>{const rows=data.dna.tests.filter(r=>r.contrast===dc);follow.replaceChildren(table(rows,[['module','Set',label],['mapped','Mapped'],['NES','NES',v=>fmt(v,3)],['family_fdr','24-test q',sci],['robustness','Direction class']]));};
  const chooser=select('DNA follow-up contrast',Object.entries(contrasts),dc,v=>{dc=v;renderTests();});body.insertBefore(chooser,follow);renderTests();
  body.append(note('DNA repair remains robust at both sampled days after removing telomere genes. Telomere-minus-DNA-repair is positive at both days but meets the new q threshold only at Day 1. DNA replication is enriched at both days, with block-dependent Day-3 direction. E2F, G2M and mitotic spindle do not meet the 24-test threshold. These mixed findings limit a repair-specific interpretation.'),downloadButton(data.dna.tests,'post-hoc-dna-24-tests.csv'));
  const variants=el('details');variants.append(el('summary','','Inspect all 240 follow-up results'),table(data.dna.sensitivities,[['module','Set',label],['contrast','Contrast',v=>contrasts[v]],['variant','Variant'],['NES','NES',v=>fmt(v,3)],['family_fdr','24-test q',sci]]),downloadButton(data.dna.sensitivities,'post-hoc-dna-all-variants.csv'));body.append(variants);
  body.append(heading('Concordance across sampled days','Descriptive correlations among selected leading-edge genes sharing the same controls. No correlation p-values or persistence claim.'));
  const points=data.dna.genes,lim=Math.max(1,...points.flatMap(g=>[Math.abs(g.day1_log2FoldChange),Math.abs(g.day3_log2FoldChange)]));const plot=svg(640,350,'Day-1 and Day-3 DNA-maintenance leading-edge gene effects');const px=v=>336+v/lim*260,py=v=>165-v/lim*125;
  line(plot,px(-lim),py(0),px(lim),py(0));line(plot,px(0),py(-lim),px(0),py(lim));line(plot,px(-lim),py(-lim),px(lim),py(lim),{'stroke-dasharray':'4 4'});
  for(const v of [-lim,0,lim]){text(plot,px(v),310,fmt(v),{'text-anchor':'middle'});text(plot,58,py(v)+4,fmt(v),{'text-anchor':'end'});}
  for(const g of points){const dot=svgNode('circle',{cx:px(g.day1_log2FoldChange),cy:py(g.day3_log2FoldChange),r:4,fill:g.in_telomere_le_union?'#a45845':'#317b82','fill-opacity':.8,tabindex:0,role:'button','aria-label':`Inspect concordance gene ${g.gene}`});dot.append(svgNode('title',{},`${g.gene} · D1 ${fmt(g.day1_log2FoldChange,4)} · D3 ${fmt(g.day3_log2FoldChange,4)}`));dot.onclick=()=>go('genes',g.gene);dot.onkeydown=e=>{if(e.key==='Enter'){go('genes',g.gene);}};plot.append(dot);}
  text(plot,320,341,'Day 1 / common control · log₂ fold change',{'text-anchor':'middle'});text(plot,15,167,'Day 3 / common control · log₂ fold change',{transform:'rotate(-90 15 167)','text-anchor':'middle','font-size':11});body.append(plot,note('Rust: telomere leading-edge union (including overlap); teal: DNA-repair leading-edge union only. Dashed line: equal estimates. Click a point to open the archived gene estimates.'),table(data.dna.concordance,[['selection','Gene selection',label],['statistic','Statistic'],['n','N genes'],['spearman','Spearman ρ',v=>fmt(v,3)],['same_sign_n','Same sign'],['positive_both_n','Positive both']]),downloadButton(data.dna.genes,'dna-cross-day-gene-effects.csv'));
  const panel=el('details');panel.append(el('summary','','Canonical gene panel · includes absent and mixed results'),note('Transcriptome-wide gene FDR from the original fits; no new panel-specific tests. H2AX/H2AFX are listed as source-symbol checks, not counted as separate biological evidence. TERT absence is not a measured null.'),table(data.dna.panel,[['gene','Gene'],['contrast','Contrast',v=>contrasts[v]],['availability','Availability'],['log2FoldChange','log₂FC',v=>fmt(v,3)],['gene_fdr','Original gene FDR',sci]]),downloadButton(data.dna.panel,'dna-canonical-panel.csv'));body.append(panel);
 }

 function methods(){
  body.append(heading('Methods, provenance & reuse','A static view of an archived analysis. Browser interactions select and display results; they do not refit DESeq2, rerun enrichment or create new confirmatory tests.'));
  const sections=[['Experimental unit','23 source libraries were pooled into nine block × condition profiles. There are three differentiation blocks and two genetic backgrounds. Cells, genes and libraries are not independent biological replicates.'],['Model and multiplicity','DESeq2 ~ block + condition; unshrunken Wald ranks; fgseaMultilevel. The five primary pathways and three contrasts form one 15-test BH family. Secondary (21 tests), exploratory (6 tests), post-primary targeted (8 tests) and post hoc DNA-maintenance (24 tests) families are separate.'],['Temporal interpretation','Both sampled days are compared with the same available controls. Control harvest-day labels are missing, so treated Day 3 / Day 1 is not a treatment-by-time interaction.'],['Scope of the observation','Transcriptional enrichment does not establish respiration, ATP production, redox state, resilience, telomere protection or a mechanism linking these cultures to human outcomes.'],['Figure 3 construction','DESeq2 VST with blind=FALSE; within-gene z-scores over nine explicitly ordered profiles. Expression and effect colors saturate at ±2.5 and ±1.5. Functional groups are project display assignments, not new enrichment families. All 113 genes were selected from OXPHOS leading edges.'],['Archive','Version 1.0.0 · https://doi.org/10.5281/zenodo.22843281']];for(const[t,p]of sections){const c=el('section','method-card');c.append(el('h3','',t),el('p','',p));body.append(c);}
  const citation=el('section','citation-card');citation.append(el('h3','','Source-study citation'),el('p','','Schmidt M, Hoffrichter A, Davoudi M, Horschitz S, Lau T, Meinhardt MW, Spanagel R, Ladewig J, Köhr G, Koch P. (2026). Psilocin fosters neuroplasticity in iPSC-derived human cortical neurons. eLife, 14, RP104006. https://doi.org/10.7554/eLife.104006.3'));body.append(citation);
  const links=el('p');for(const[t,u]of [['Original article',provenance.article],['Author RNA-seq repository',provenance.source],['Dryad phenotype record','https://doi.org/10.5061/dryad.xsj3tx9w3'],['Archived reanalysis','https://doi.org/10.5281/zenodo.22843281']]){const a=el('a','source-link',t+' ↗');a.href=u;a.target='_blank';a.rel='noopener';links.append(a);}body.append(links,el('h3','','Frozen plan record'));
  const pre=el('pre','hash-record',JSON.stringify(provenance.freeze,null,2));body.append(pre,el('h3','','Exact input checksums'),table(Object.entries(provenance.inputs).map(([path,sha256])=>({path,sha256})),[['path','Source file'],['sha256','SHA-256']]),button('↓ Download provenance JSON',()=>download('provenance.json',JSON.stringify(provenance,null,2),'application/json'),'secondary'),button('↓ Download complete atlas JSON',()=>download('atlas.json',JSON.stringify(data),'application/json'),'secondary'));
 }
 render();return root;
}
