const url = "https://psilocybin-research.github.io/psilocin-human-neuron-transcriptomics/";
const image = "https://raw.githubusercontent.com/psilocybin-research/psilocin-human-neuron-transcriptomics/main/docs/images/atlas-overview.png";
const title = "Psilocin human-neuron transcriptomic atlas";
const description = "Explore the primary OXPHOS-centered signature and bounded exploratory DNA-repair and telomere-maintenance findings from an independent secondary analysis of the Schmidt et al. human-neuron RNA-seq study.";
const sourceAuthors = [
  "Malin Schmidt", "Anne Hoffrichter", "Mahnaz Davoudi", "Sandra Horschitz",
  "Thorsten Lau", "Marcus W. Meinhardt", "Rainer Spanagel", "Julia Ladewig",
  "Georg Köhr", "Philipp Koch"
].map(name => ({"@type": "Person", name}));
const structuredData = {
  "@context": {
    "@vocab": "https://schema.org/",
    "prov": "http://www.w3.org/ns/prov#",
    "dcterms": "http://purl.org/dc/terms/"
  },
  "@type": "WebApplication",
  "@id": url,
  name: title,
  headline: "A brief perturbation. A broad transcriptional signature.",
  description,
  url,
  applicationCategory: "ScientificApplication",
  operatingSystem: "Any web browser",
  version: "1.0.0",
  author: {
    "@type": "Person",
    name: "Christopher B. Germann",
    identifier: "https://orcid.org/0000-0002-1573-4651",
    affiliation: {
      "@type": "Organization",
      name: "Faculty of Health, School of Medicine, University of Witten/Herdecke"
    }
  },
  codeRepository: "https://github.com/psilocybin-research/psilocin-human-neuron-transcriptomics",
  citation: {"@id": "https://doi.org/10.5281/zenodo.22843281"},
  isBasedOn: [
    {
      "@type": "ScholarlyArticle",
      "@id": "https://doi.org/10.7554/eLife.104006",
      name: "Psilocin fosters neuroplasticity in iPSC-derived human cortical neurons",
      author: sourceAuthors,
      license: "https://creativecommons.org/licenses/by/4.0/"
    },
    {
      "@type": "Dataset",
      "@id": "https://doi.org/10.5061/dryad.xsj3tx9w3",
      name: "Source research data for Psilocin fosters neuroplasticity in iPSC-derived human cortical neurons",
      creator: sourceAuthors,
      license: "https://creativecommons.org/publicdomain/zero/1.0/"
    },
    {
      "@type": "SoftwareSourceCode",
      "@id": "https://archive.softwareheritage.org/swh:1:dir:c847a8a51074c59d651e3258cf1355936e921048/",
      name: "Original Hoffrichter/Schmidt RNA-seq analysis code",
      author: {"@type": "Person", name: "Anne Hoffrichter"},
      identifier: "swh:1:dir:c847a8a51074c59d651e3258cf1355936e921048",
      codeRepository: "https://github.com/ahoffrichter/Schmidt_et_al_2025/tree/c565709affafbea09406bd7b42fe494f08db6cce",
      license: "https://spdx.org/licenses/MIT.html"
    }
  ],
  "prov:wasDerivedFrom": [
    {"@id": "https://doi.org/10.7554/eLife.104006"},
    {"@id": "https://doi.org/10.5061/dryad.xsj3tx9w3"},
    {"@id": "https://archive.softwareheritage.org/swh:1:dir:c847a8a51074c59d651e3258cf1355936e921048/"}
  ],
  "dcterms:provenance": "Independent secondary analysis by Christopher B. Germann of public experimental data generated by Schmidt et al.; newly generated outputs comprise analysis code, derived tables, figures, tests, and this interactive atlas.",
  license: [
    "https://spdx.org/licenses/MIT.html",
    "https://creativecommons.org/licenses/by/4.0/"
  ],
  usageInfo: "https://github.com/psilocybin-research/psilocin-human-neuron-transcriptomics/blob/main/LICENSE.md",
  image
};

const head = `
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 32 32%22%3E%3Crect width=%2232%22 height=%2232%22 rx=%226%22 fill=%22%23245b50%22/%3E%3Ctext x=%2216%22 y=%2223%22 text-anchor=%22middle%22 fill=%22white%22 font-size=%2223%22%3EP%3C/text%3E%3C/svg%3E">
<link rel="canonical" href="${url}">
<link rel="cite-as" href="https://doi.org/10.5281/zenodo.22843281">
<link rel="describedby" type="application/vnd.datacite.datacite+json" href="https://api.datacite.org/dois/10.5281/zenodo.22843281">
<link rel="author" href="https://orcid.org/0000-0002-1573-4651">
<link rel="license" href="https://github.com/psilocybin-research/psilocin-human-neuron-transcriptomics/blob/main/LICENSE.md">
<meta name="description" content="${description}">
<meta name="DC.identifier" content="https://doi.org/10.5281/zenodo.22843281">
<meta name="DC.language" content="en">
<meta name="author" content="Christopher B. Germann">
<meta name="keywords" content="psilocin, psilocybin, transcriptomics, RNA-seq, human cortical neurons, oxidative phosphorylation, OXPHOS, redox biology, neuroplasticity, reproducible research">
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1">
<meta name="citation_title" content="A brief perturbation. A broad transcriptional signature: psilocin human-neuron transcriptomics">
<meta name="citation_author" content="Germann, Christopher B.">
<meta name="citation_publication_date" content="2026-09-19">
<meta name="citation_doi" content="10.5281/zenodo.22843281">
<meta name="citation_keywords" content="psilocin; psilocybin; transcriptomics; RNA-seq; human cortical neurons; oxidative phosphorylation; redox biology">
<meta name="citation_reference" content="Schmidt M, Hoffrichter A, Davoudi M, et al. (2026). Psilocin fosters neuroplasticity in iPSC-derived human cortical neurons. eLife. doi:10.7554/eLife.104006">
<meta name="dcterms.type" content="InteractiveResource">
<meta name="dcterms.creator" content="Germann, Christopher B.">
<meta name="dcterms.bibliographicCitation" content="doi:10.5281/zenodo.22843281">
<meta name="dcterms.source" content="doi:10.7554/eLife.104006">
<meta name="dcterms.source" content="doi:10.5061/dryad.xsj3tx9w3">
<meta name="dcterms.source" content="swh:1:dir:c847a8a51074c59d651e3258cf1355936e921048">
<meta name="dcterms.provenance" content="Independent secondary analysis by Christopher B. Germann of experimental data generated by Schmidt et al.; not the original experimental dataset or original analysis.">
<meta name="dcterms.license" content="https://github.com/psilocybin-research/psilocin-human-neuron-transcriptomics/blob/main/LICENSE.md">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Psilocybin Research">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${image}">
<meta property="og:image:alt" content="Overview of the interactive psilocin human-neuron transcriptomic atlas">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${title}">
<meta name="twitter:description" content="${description}">
<meta name="twitter:image" content="${image}">
<script type="application/ld+json">${JSON.stringify(structuredData)}</script>`;

export default {
  title: "Psilocin · transcriptomic atlas",
  root: "src", output: "dist", theme: "light", sidebar: false, toc: false,
  globalStylesheets: [],
  style: "style.css", header: "", footer: "", head
};
